apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subjects-persistent-claim
spec:
  storageClassName: app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
