apiVersion: v1
kind: PersistentVolume
metadata:
  name: subjects-persistence
  labels:
    app: subjects
spec:
  storageClassName: app-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
